-- Deprecated India-specific UPI migration retained for migration history.
-- New Congo-first deployments use Mobile Money and do not require these columns.
-- Existing databases may keep the legacy columns temporarily; application code no longer reads or writes them.
